### ISSUE TITLE
Fixed boundary boundary checking

### ISSUE THREAD

**Issue by Demirrr** [IssamLaradji/sls#10]
Hello all,

I was wondering whether increasing  this fixed 100 iterations in [here](https://github.com/IssamLaradji/sls/blob/e2522d5ad765e2fc5826c11518914d820add9d4f/sls/sls.py#L97) would improve the results even further?

**Comment by IssamLaradji** [comment]
In our experiments, we found that part of the optimization converges very quickly, often in about 5 iterations, so 100 iterations seemed more than enough.

Of course, that's dataset and problem specific and it might be worth having it as a hyperparameter.

**Comment by Demirrr** [comment]
Cheers!
