### ISSUE TITLE
CUDA device

### ISSUE THREAD

**Issue by mloubout** [IssamLaradji/sls#7]
There is two lines that creates tensor on the wrong device with multi device nodes

https://github.com/IssamLaradji/sls/blob/ff09a239417828c61700ea57d148bef939e50b17/sls/sls_acc.py#L147

https://github.com/IssamLaradji/sls/blob/ff09a239417828c61700ea57d148bef939e50b17/sls/sls_acc.py#L156

These should not use `.cuda()` but `.to(p_current.device)` and `.to(p_model.data.device)`

**Comment by IssamLaradji** [comment]
Thanks @mloubout . Comments like these help me make it a habit to use `.to(device)` instead of `.cuda()` . Good catch!
